### ISSUE TITLE
black doesn't respect the line length in a list with comments

### ISSUE THREAD

**Issue by Lukas0907** [ambv/black#84] opened 2018-03-28 10:20 UTC
Hi,

I've stumbled upon the following problem. Trying to reformat the code:

```python
test = [
    (None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)
    # et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea t
]
```

Produces:

```
test_black.py already well formatted, good job.
```

Which is clearly not the case since the lines are too long. I think it has something to do with the comment in the list.

Operating system: Ubuntu 16.04
Python version: 3.6.1
Black version: master
Does also happen on master: yes

**Comment by carljm** [comment] 2018-03-28 16:22
Hi, thanks for the report! This is a duplicate of issue #22.

**Closed by carljm** 2018-03-28 16:22 UTC
