### ISSUE TITLE
Style Change RFC: Block-indent fluent line breaks

### ISSUE THREAD

**Issue by quodlibetor** [ambv/black#345] opened 2018-06-12 22:16 UTC
In #344 I thought that there was a bug in the formatting, but it turned out I was just confused. I think that fluent interfaces could benefit from an indent of `.`-prefixed lines.

The specific rule that I am proposing is:

> If there is an attribute and method chain that must be broken onto multiple lines, then break at the first dot that precedes a method call and indent 4 spaces from the previous line for all future method calls.

consider the difference:

```python
def current():
    return [
        x
        for y in m.Package.query.with_entities(m.Package.name)
        .order_by(m.Package.name.asc())
        .all()
        for x in y
    ]
```

```python
def proposed():
    return [
        x
        for y in m.Package.query
            .with_entities(m.Package.name)
            .order_by(m.Package.name.asc())
            .all()
        for x in y
    ]
```

**Comment by ambv** [comment] 2018-06-20 18:19
This is a duplicate of #147.

**Closed by ambv** 2018-06-20 18:19 UTC
Labels: design
