### ISSUE TITLE
Really long for lines with can produce different code on the second pass.

### ISSUE THREAD

**Issue by bryanhelmig** [ambv/black#358] opened 2018-06-15 22:17 UTC
Simple reproduction case:

```python
some_dictionary_goes_here = dict()
for some_long_key_goes_here, some_long_value_goes_right_here in some_dictionary_goes_here.get('someval', {}).items():
    pass
```

And you get an error message like:

```
error: cannot format example.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: /var/folders/sc/373kncn649dsmcmyq47hh8_r0000gn/T/be0glk_yocel.log
```

The diff:

```diff
--- source
+++ first pass
@@ -1,5 +1,11 @@


 some_dictionary_goes_here = dict()
-for some_long_key_goes_here, some_long_value_goes_right_here in some_dictionary_goes_here.get('someval', {}).items():
+for (
+    some_long_key_goes_here,
+    some_long_value_goes_right_here,
+) in some_dictionary_goes_here.get(
+    "someval", {}
+).items():
     pass
+
--- first pass
+++ second pass
@@ -2,10 +2,8 @@

 some_dictionary_goes_here = dict()
 for (
     some_long_key_goes_here,
     some_long_value_goes_right_here,
-) in some_dictionary_goes_here.get(
-    "someval", {}
-).items():
+) in some_dictionary_goes_here.get("someval", {}).items():
     pass
```

Operating system: Mac OS X
Python version: Python 3.6.5
*Black* version: 18.6b2
Does also happen on master: yes

**Comment by ambv** [comment] 2018-06-15 22:19
Thanks for your report and sorry for your trouble! This is a duplicate of https://github.com/ambv/black/issues/267 and will be fixed soon.

**Closed by ambv** 2018-06-15 22:19 UTC
