### ISSUE TITLE
relative imports convert `. .` to `..`

### ISSUE THREAD

**Issue by maxim-lian** [ambv/black#6] opened 2018-03-14 22:11 UTC
Excited about the effort - thanks for kicking this off! Hopefully of what yapf once dreamed

One quick issue when scanning the output: is this intended?

```
# existing
from ..convert import from_iris

# black
from . .convert import from_iris
```

**Comment by ambv** [comment] 2018-03-14 22:44
No, this is not intended. Extra spaces might appear here and there for a while. That's the safe default for unrecognized code patterns. I can reproduce this and will fix shortly.

**Comment by ambv** [comment] 2018-03-15 18:22
Thank you for your report, this is now fixed!

**Closed** 2018-03-15 18:22 UTC

**Comment by maxim-lian** [comment] 2018-03-15 19:55
Thank you for such a fast turnaround!
