### ISSUE TITLE
Invalid code produced

### ISSUE THREAD

**Issue by jivid** [ambv/black#241] opened 2018-05-21 17:02 UTC
Operating system: macOS 10.13.3
Python version: 3.6.2
Black version: 18.5b0
Does also happen on master: Yes

Full repro commands: https://gist.github.com/jivid/daac0d2fa478e8acf1a1980c88de5044

The file below produces an error saying `Black produced invalid code`:
```python
#!/usr/bin/env python3

import math

# fmt: off

sql = (
    "SELECT * "
    "FROM ("
        "SELECT * "
        "FROM foo "
    ") AS bar"
)

# fmt: on

print(math.floor(1.5))
```

If I remove the `fmt` comments, it works just fine.

**Comment by ambv** [comment] 2018-05-21 17:08
Sorry for your trouble. This is a duplicate of #224.

**Comment by jivid** [comment] 2018-05-21 17:09
Thanks @ambv. I should have searched more thoroughly before reporting

**Closed by ambv** 2018-05-21 17:08 UTC
