### ISSUE TITLE
Black puts standalone comments inside short exploded expressions *after* the expression

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ambv/black#62] opened 2018-03-22 14:52 UTC
gotten:
```diff
         cwd=str(cwd),
-        env=_always_strings(dict(
-            os.environ,
-            # try to disable i18n
-            LC_ALL='C',
-            LANGUAGE='',
-            HGPLAIN='1',
-        ))
+        env=_always_strings(dict(os.environ, LC_ALL='C', LANGUAGE='', HGPLAIN='1')),
+        # try to disable i18n
     )
```

**Comment by ambv** [comment] 2018-03-22 16:47
This is by design. Black changed 7 lines into 2 lines. Your code will be clearer if you put the standalone comment in front of the line.

I'll leave that open because currently we're putting the standalone comment *after* the line it's commenting which is contrary to the expectation. But the fix will be to put this comment in front of the reformatted line.

**Comment by carljm** [comment] 2018-03-23 15:57
This is a duplicate of #22.

**Closed by carljm** 2018-03-23 15:57 UTC
Labels: bug, comments
