### ISSUE TITLE
Ugly code formatting for multiple contexts

### ISSUE THREAD

**Issue by louisabraham** [ambv/black#592] opened 2018-11-03 15:53 UTC
```
    with ThreadPoolExecutor(max_workers=n_locations) as executor, tqdm(
        total=n_locations
    ) as pbar:
```

This is how black formats my code. It makes it quite unreadable.

**Comment by bcb** [comment] 2018-11-07 00:18
This is more of a Python issue.

It would be better if `with` took a parenthesized tuple of contexts.

```
with (
    ThreadPoolExecutor(max_workers=n_locations) as executor,
    tqdm(total=n_locations) as pbar,
):

**Comment by bcb** [comment] 2018-11-07 00:20
Also duplicate of #557

**Comment by JelleZijlstra** [comment] 2018-11-07 01:35
Closing as a dupe of #557.

**Closed by JelleZijlstra** 2018-11-07 01:35 UTC
