### ISSUE TITLE
How can I break lines in vim?

### ISSUE THREAD

**Issue by RidaAyed** [ambv/black#342] opened 2018-06-12 14:18 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: *Linux Arch*
Python version: *3.6.65*
*Black* version: Black, version 18.6b2 on Python 3.6.5 (default, May 11 2018, 04:00:52)
[GCC 8.1.0].   
Does also happen on master: :thinking: 

To answer the last question, follow these steps:
* create a new virtualenv (make sure it's the same Python version);
* clone this repository;
* run `pip install -e .`;
* make sure it's sane by running `python setup.py test`; and
* run `black` like you did last time.

## How can I break lines in vim?

Hi

How can I break lines using `:Black` to format from this?

```python
headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        }
```

to that:  

```python
headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 \
        (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
        }
```
P.S. Can't answer last question due to:
```
(blacktest-M_xMekwm) ra @ ~/dev/blacktest/black
master└─ $ pip install -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
```

**Comment by JelleZijlstra** [comment] 2018-06-12 14:30
You need to do `pip install -e .` to install from master (don't forget the dot). Is there documentation that has the wrong command?

Breaking up long strings is already an open issue: #182.

**Comment by RidaAyed** [comment] 2018-06-12 14:55
@JelleZijlstra Indeed I've missed the `.`

**Comment by ambv** [comment] 2018-06-13 07:13
@RidaAyed, the break you're suggesting doesn't do what you think. Since it's a backslash inside a string literal, all the other extra whitespace will be preserved as extra spaces inside the string. If you omit the extra spaces, the line will just wrong being dedented compared to the rest of the code.

What you want is this:
```py3
headers = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
    ),
}
```

If you're question is about "how to invoke Black from Vim", then the answer to that is "with :Black or ,=".

**Comment by RidaAyed** [comment] 2018-06-13 13:09
Thank you @ambv Lukasz. Yes, you're right, how can I get these lines breaked as you outlined?

**Comment by JelleZijlstra** [comment] 2018-06-13 15:01
That's the issue I linked above; Black doesn't implement it yet.

**Comment by ambv** [comment] 2018-06-13 18:50
@JelleZijlstra, true, but if you format this yourself, Black will keep it.

**Comment by ambv** [comment] 2018-06-20 18:06
Closing this as a duplicate of #182. If there's anything more that's actionable here, please open a new issue.

**Closed by ambv** 2018-06-20 18:06 UTC
