### ISSUE TITLE
Consider not breaking line on outermost parenthesis

### ISSUE THREAD

**Issue by cdeil** [ambv/black#500] opened 2018-09-06 16:16 UTC
First of all - thank you for making black!
I'm applying it to my main project (Gammapy) today.

There are a few examples where I think that black gives non-ideal results, and wanted to mention them here. If those have been discussed before, I apologise, please just close this issue.

I think this is nice:
```python
things = OrderedDict([
    ('ham', 'spam'),
    ('bla bla bla bla', 'some more text here'),
])
```
and putting `[` and `]` on a separate line like black does is not an improvement:
```python
things = OrderedDict(
    [
        ("ham", "spam"),
        ("bla bla bla bla", "some more text here"),
    ]
)
```

I read through the black description, and see that this is intended behaviour to always add line breaks on the outermost parenthesis. Is it possible / up for debate to change this in some cases?

This is another case:
```python
text  = """
Hello hallo
allo allo
"""[1:-1]
```
where black gives this output:
```
text = """
Hello hallo
allo allo
"""[
    1:-1
]
```
and I think the input formatting is better readable than the black output.

**Comment by zsol** [comment] 2018-09-07 19:47
I agree that the formatting in your second example is terrible. That's because black treats those multiline strings as if they never fit a line. #256 tracks that.

I'm not so sure about your first example. I like that black makes it very explicit that we're passing a list instead of two parameters. On the other hand I see where you're coming from as the result is a bit more verbose.

**Comment by ambv** [comment] 2018-09-26 16:46
Thanks for your report! I will close this as a duplicate of #256. We'll track the fix there.

We won't be changing formatting of consecutive bracket pairs.

**Closed by ambv** 2018-09-26 16:46 UTC
Labels: design
