### ISSUE TITLE
Incorrect reformatting when using type comments

### ISSUE THREAD

**Issue by ybastide** [ambv/black#383] opened 2018-06-28 15:20 UTC
Operating system: Linux
Python version: 3.6
*Black* version: 18.6b4
Does also happen on master: yes

This function:
```python
def foo(
        x,  # type: str
):
    pass
```

is formatted as:
```python
def foo(x, ):  # type: str
    return x
```

**Comment by zsol** [comment] 2018-06-28 15:38
Thanks for reporting, this is a duplicate of #282

**Closed by zsol** 2018-06-28 15:38 UTC
