### ISSUE TITLE
Implicit string literal concatenation and indentation within structures

### ISSUE THREAD

**Issue by acdha** [ambv/black#306] opened 2018-06-06 18:04 UTC
I was updating our internal style guide to recommend using Black everywhere and ran into one less than satisfying case with long string literals nested in something like a `dict` declaration using black, version 18.6b1.

Here's an example input with a few variations:

```python

# Single strings won't be wrapped:
print({
    "this key is really long and so is the value": "but it still fits on one line",
    "but this key is even longer and": "the value is a long literal which should be on multiple lines for clarity",
})

# The second string literal in the value should wrap:
print({
    "this key is really long and so is the value": "but it still fits on one line",
    "but this key is even longer and": "the value is a long literal which should be on multiple" " lines for clarity",
})

# Using parentheses should wrap and indent:
print({
    "this key is really long and so is the value": "but it still fits on one line",
    "but this key is even longer and": ("the value is a long literal which should be on multiple" " lines for clarity"),
})

# Doing the same thing as a list should be similar:
print([
    ( "this key is really long and so is the value", "but it still fits on one line", ),
    ( "but this key is even longer and", "the value is a long literal which should be on multiple" " lines for clarity"),
])

# Using parentheses around the literal should wrap and indent within the
# parentheses:

print([
    ( "this key is really long and so is the value", "but it still fits on one line", ),
    ( "but this key is even longer and", ( "the value is a long literal which should be on multiple" " lines for clarity"), ),
])

```

Black 18.6b1 produces this:

```diff
--- example.py	2018-06-06 17:57:11 +0000
+++ example.py	2018-06-06 17:57:42.930371 +0000
@@ -17,36 +17,66 @@
         "should be indented": "at the same level",
     }
 )
 
 # Single strings won't be wrapped:
-print({
-    "this key is really long and so is the value": "but it still fits on one line",
-    "but this key is even longer and": "the value is a long literal which should be on multiple lines for clarity",
-})
+print(
+    {
+        "this key is really long and so is the value": "but it still fits on one line",
+        "but this key is even longer and": "the value is a long literal which should be on multiple lines for clarity",
+    }
+)
 
 # The second string literal in the value should wrap:
-print({
-    "this key is really long and so is the value": "but it still fits on one line",
-    "but this key is even longer and": "the value is a long literal which should be on multiple" " lines for clarity",
-})
+print(
+    {
+        "this key is really long and so is the value": "but it still fits on one line",
+        "but this key is even longer and": "the value is a long literal which should be on multiple"
+        " lines for clarity",
+    }
+)
 
 # Using parentheses should wrap and indent:
-print({
-    "this key is really long and so is the value": "but it still fits on one line",
-    "but this key is even longer and": ("the value is a long literal which should be on multiple" " lines for clarity"),
-})
+print(
+    {
+        "this key is really long and so is the value": "but it still fits on one line",
+        "but this key is even longer and": (
+            "the value is a long literal which should be on multiple"
+            " lines for clarity"
+        ),
+    }
+)
 
 # Doing the same thing as a list should be similar:
-print([
-    ( "this key is really long and so is the value", "but it still fits on one line", ),
-    ( "but this key is even longer and", "the value is a long literal which should be on multiple" " lines for clarity"),
-])
+print(
+    [
+        (
+            "this key is really long and so is the value",
+            "but it still fits on one line",
+        ),
+        (
+            "but this key is even longer and",
+            "the value is a long literal which should be on multiple"
+            " lines for clarity",
+        ),
+    ]
+)
 
 # Using parentheses around the literal should wrap and indent within the
 # parentheses:
 
-print([
-    ( "this key is really long and so is the value", "but it still fits on one line", ),
-    ( "but this key is even longer and", ( "the value is a long literal which should be on multiple" " lines for clarity"), ),
-])
+print(
+    [
+        (
+            "this key is really long and so is the value",
+            "but it still fits on one line",
+        ),
+        (
+            "but this key is even longer and",
+            (
+                "the value is a long literal which should be on multiple"
+                " lines for clarity"
+            ),
+        ),
+    ]
+)

```

Ignoring the issue of splitting or joining literals, it seems like the non-parenthesized values could be indented in a way which more clearly indicates the structure.

For example, instead of

```python
    {
        "this key is even longer and": "the value is a long literal which should be on multiple"
        " lines for clarity",
    }
```

it seems better to read if it was indented either one stop or to match the previous literal:

```python
    {
        "this key is even longer and": "the value is a long literal which should be on multiple"
            " lines for clarity",
    }
```

```python
    {
        "this key is even longer and": "the value is a long literal which should be on multiple"
                                       " lines for clarity",
    }
```

or if Black would insert parentheses so there's no chance that the wrapped concatenation would be seen as the start of a new key rather than a continuation of the previous value.

**Comment by ambv** [comment] 2018-06-06 22:51
I agree that in the case of dictionary values, if they are implicitly joined strings, they should be differentiated from dictionary keys. Wrapping those cases in optional parentheses is what I'll likely do.

**Comment by acdha** [comment] 2018-06-07 13:15
Wrapping in parentheses seems like a good catch-all for situations like this. I ended up picking that style after opening this issue since it works with the current release and it is definitely unambiguous.

**Comment by ambv** [comment] 2018-06-10 02:17
I'll close this as a duplicate of #147 then.

**Closed by ambv** 2018-06-10 02:17 UTC
Labels: enhancement
