### ISSUE TITLE
Black could split long import statements

### ISSUE THREAD

**Issue by sfermigier** [ambv/black#69] opened 2018-03-23 07:45 UTC
Operating system: Mac OS
Python version: 3.6.4
Black version: 18.3a3
Does also happen on master: yes

---

Black joins long import statements, like in this example:

```
-from flask import Blueprint, Flask, _request_ctx_stack, abort, \
-    appcontext_pushed, current_app, g, render_template, request, \
-    request_started
+from flask import Blueprint, Flask, _request_ctx_stack, abort, appcontext_pushed, current_app, g, render_template, request, request_started
```

In this case, and unlike in issue https://github.com/ambv/black/issues/67 , it's OK to ignore the backslashes, but it would be better if the line was split to the proper length afterwards.

Since isort (https://pypi.python.org/pypi/isort) does a very good job at sorting and formatting imports, it's not a big deal if one is willing to run `isort` after `black`. OTOH, since Black aims at providing an integrated solution, Black should probably do the splitting (and leave the sorting to isort, since this can have side effects).

**Comment by ambv** [comment] 2018-03-23 15:35
Black doesn't yet put/remove organizational parentheses around such expressions automatically. If you do it manually, it will split that line just fine.

**Comment by carljm** [comment] 2018-03-23 15:48
This is a duplicate of #4.

**Closed by carljm** 2018-03-23 15:48 UTC
