### ISSUE TITLE
Parse error  complains about the wrong thing.

### ISSUE THREAD

**Issue by nat-n** [ambv/black#813] opened 2019-04-24 09:28 UTC
Operating system: macOS 10.14.1
Python version: 3.6.4
*Black* version: 18.9b0
Does also happen on master: Yes at https://black.now.sh/?version=master

Test case:
```
class Foo:
    def print(self, msg):
        print("Foo says:", msg)

    def work(self):
        self.print("Nay!")
,
```

Expected it to complain about the stray comma on line 7. 
Instead it complains about defining a method called print: `Cannot parse: 2:8:     def print(self, msg):`
When I remove the comma it no longer has a problem parsing the rest of it.

Will similarly complain about the use of `self.print(...` if it  encounters that first.

**Comment by zsol** [comment] 2019-04-24 15:16
dupe of #423

**Closed by zsol** 2019-04-24 15:16 UTC
