### ISSUE TITLE
Strings spanning multiple lines

### ISSUE THREAD

**Issue by ikatanic** [ambv/black#98] opened 2018-04-03 10:44 UTC
Hi, thanks for creating black. I love it!

I have one issue though:
```
x = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
is formatted to:
```
x = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
i.e. one very long line.
Is this wanted behaviour?

**Comment by SethMichaelLarson** [comment] 2018-04-03 16:54
Should probably use parens.
```python
x = (
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
)
```

**Comment by ambv** [comment] 2018-04-03 21:00
Yes, put parentheses and Black will format this correctly. Next release will put them and remove them automatically in some obvious cases.

**Comment by ambv** [comment] 2018-04-03 21:00
See #4.

**Comment by carljm** [comment] 2018-04-04 21:45
Closing this as a dupe of #4, since I don't think it's independently actionable?

**Closed by carljm** 2018-04-04 21:45 UTC
