### ISSUE TITLE
Black removes trailing comma

### ISSUE THREAD

**Issue by skorokithakis** [ambv/black#368] opened 2018-06-21 14:30 UTC
Operating system: Ubuntu
Python version: 3.6
*Black* version: 18.6b3
Does also happen on master: Probably

Black removes the trailing comma and `isort` puts it back in. It seems to me like Black shouldn't, as per the README:

```
from test.case import (
    some_long_name_that_wont_fit_one_line_because_its_long_oh_so_very_long,
)
```

**Comment by ambv** [comment] 2018-06-21 19:04
Agreed, this is a bug that I will fix in the next release. Thanks for flagging!

This is a duplicate of https://github.com/ambv/black/issues/250.

**Closed by ambv** 2018-06-21 19:04 UTC
