### ISSUE TITLE
Unnecessary empty liens around functions inside an if statement

### ISSUE THREAD

**Issue by expobrain** [ambv/black#384] opened 2018-06-29 14:35 UTC
Operating system: OSX 10.13.5
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

When formatting this code:
```
if x:
    def y():
        pass
else:
    def z():
        pass
```

`black` adds some unnecessary empty lines in around then functions:

```
if x:

    def y():
        pass


else:

    def z():
        pass
```

**Comment by zsol** [comment] 2018-06-29 14:53
Looks like this is a dupe of #377. Thanks for reporting!

**Closed by zsol** 2018-06-29 14:53 UTC
