### ISSUE TITLE
black adds trailing comma despite using --target-version py35

### ISSUE THREAD

**Issue by bjoernricks** [ambv/black#759] opened 2019-03-15 11:27 UTC
Hi,

black 19.3b0 adds trailing commas for function signatures containing `*` despite setting target version 3.5. This creates invalid code for python 3.5 which will raise a SyntaxError. Setting
target version to py34 or using the auto detection doesn't add a trailing comma in this case.

```python3
def foo_func(bar, *, lorem=None, ipsum=None, dolor=None, sit=None, amet=None, consectetur=None):
    print('lorem ipsum dolor sit amet')
```
running
```sh
> black --target-version py35 --line-length 80 foo.py
```
creates

```python3
def foo_func(
    bar,
    *,
    lorem=None,
    ipsum=None,
    dolor=None,
    sit=None,
    amet=None,
    consectetur=None,
):
    print("lorem ipsum dolor sit amet")
``` 

Operating system: Ubuntu 18.04
Python version: Python 3.5/3.6
*Black* version: 
```sh
> black --version
black, version 19.3b0
```
Does also happen on master: yes

**Comment by JelleZijlstra** [comment] 2019-03-15 15:34
Looks like we improperly merged two different syntax changes: `f(**x,)` (trailing comma in a call) first became legal in 3.5, but `def f(**x,): pass` (trailing comma in a definition) became legal only in 3.6. I'll try to disentangle the two in the code.

**Closed** 2019-03-25 15:22 UTC

**Comment by bjoernricks** [comment] 2019-03-28 13:44
Thanks a lot!

**Comment by mikenerone** [comment] 2020-11-02 23:09
Seems like there's a regression -I'm seeing this behavior with 20.8b1. It could be something more specific: my affected function has a return type annotation.

**Comment by ichard26** [comment] 2020-11-02 23:11
@mikenerone could you please post the bug-inducing code? Might be a case of #1356.

**Comment by mikenerone** [comment] 2020-11-03 06:08
> @mikenerone could you please post the bug-inducing code? Might be a case of #1356.

I believe you right. My triggering sample below closely resembles a case shown there.
```
class LongishClassNameToHelpTriggerTheBug:
    ...


def only_seems_to_trigger_bug_if_definition_is_long_enough_to_require_wrapping(
    *some_args: LongishClassNameToHelpTriggerTheBug
) -> LongishClassNameToHelpTriggerTheBug:
    pass
```
