### ISSUE TITLE
Black fails to detect tabbed standalone comment indent correctly

### ISSUE THREAD

**Issue by jleclanche** [ambv/black#512] opened 2018-09-14 02:22 UTC
Operating system: Linux
Python version: 3.7
*Black* version: master

Running black on the following:

```py
def test():
	if 1:
		return True

	# Note: we are not returning False here because a line might have *both*
	# a leading opening bracket and a trailing closing bracket.  If the
	# opening bracket doesn't match our rule, maybe the closing will.
```

Generates:

```py
def test():
    if 1:
        return True

        # Note: we are not returning False here because a line might have *both*
        # a leading opening bracket and a trailing closing bracket.  If the
        # opening bracket doesn't match our rule, maybe the closing will.
```

**Comment by ambv** [comment] 2018-09-26 19:27
This is a duplicate of #262.

**Closed by ambv** 2018-09-26 19:27 UTC
