### ISSUE TITLE
Bad formatting of multiline f-strings

### ISSUE THREAD

**Issue by yutkin** [ambv/black#369] opened 2018-06-21 16:02 UTC
This code
```
str = f"this" \
      f"is a very" \
      f" long " \
      f"string."

print(str)
```
Black converts to
```
str = f"this" f"is a very" f" long " f"string."

print(str)
```
Why not just concatenate it to `str = f"this is a very long string."`?

black, version 18.6b3
Python 3.6.5

**Comment by zsol** [comment] 2018-06-21 16:29
This is a dupe of #26, we're going to fix it!

**Closed by zsol** 2018-06-21 16:29 UTC
