### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by normoes** [ambv/black#624] opened 2018-11-27 20:03 UTC
Please include the usage of `--exclude` into the README.

I was struggling to find how to use it:
```
black . --diff --exclude '\.venv/|\.local/|\.cache/|\.git/|migrations/'
```

I was missing the `'...'`.

**Comment by JelleZijlstra** [comment] 2018-11-28 04:41
dupe of #623

**Closed by JelleZijlstra** 2018-11-28 04:41 UTC

**Comment by normoes** [comment] 2018-11-28 04:42
Two times?
Sorry, can't remember putting it here two times :)
Thanks for closing it!
