### ISSUE TITLE
Multi-line strings possibly not corrected properly

### ISSUE THREAD

**Issue by BenjaminBossan** [ambv/black#261] opened 2018-05-26 09:53 UTC
In my code base, I usually handle long strings by breaking them within parens. When black puts the split string onto one line, it still keeps the strings separate. The example below should make it clear:

```
-            raise IndexError("arrays used as indices must be of integer "
-                             "(or boolean) type")
+            raise IndexError(
+                "arrays used as indices must be of integer " "(or boolean) type"
+            )
```

Question is: Can this be fixed or is there a reason why it needs to be this way?

Operating system: Ubuntu 18.04
Python version: 3.6
Black version: 18.5b0
Does also happen on master: yes

**Comment by zsol** [comment] 2018-05-26 12:15
This looks like a duplicate of #26
We're definitely planning to fix this but it's not trivial for the reasons pointed out in #26.

**Closed by zsol** 2018-05-26 12:15 UTC
