### ISSUE TITLE
Black does join import lines, but does not remove brackets

### ISSUE THREAD

**Issue by Aulos** [ambv/black#44] opened 2018-03-20 17:05 UTC
Code to format:

```python
from a import (
    aa,
    ab,
)
```

Black output:
```python
from a import (aa, ab)
```

Expected output:
```python
from a import aa, ab
```

Operating system: Ubuntu 17.10
Python version: 3.6.3
Black version: 18.3a2
Does also happen on master: yes

**Comment by ambv** [comment] 2018-03-20 20:07
This is a duplicate of #4 and a planned feature :-)

**Comment by Aulos** [comment] 2018-03-21 06:52
It would be nice if it was consistent.

Now code like:
```python
from a import (
    aa,
    ab,
)
from b import ba, bb
```
is transformed to 
```python
from a import (aa, ab)
from b import ba, bb
```

which looks kind of strange.

**Comment by ambv** [comment] 2018-03-21 14:53
Agreed, this will be fixed soon.

**Comment by ambv** [comment] 2018-03-21 14:53
In the mean time, as a workaround, if you manually remove the unnecessary punctuation, Black won't add it back ;-)

**Comment by ambv** [comment] 2018-03-21 14:55
The reason I'm leaving a trailing comma for single-element parenthesized expressions is that it looks like a tuple and removing it would change what your code means.

In the import case it's a false positive of course :-)

**Comment by carljm** [comment] 2018-03-23 15:56
@ambv Is there anything specifically actionable here that isn't covered by #4? Closing as a dupe; it's still linked from #4 if you want the examples.

**Closed by carljm** 2018-03-23 15:56 UTC
Labels: enhancement
