### ISSUE TITLE
multipart string left multipart

### ISSUE THREAD

**Issue by tbicr** [ambv/black#743] opened 2019-03-12 11:44 UTC
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04.5 LTS
Python version: 3.7.2
*Black* version: 18.9b0
Does also happen on master: yes

```
('test'
 'line')
```

will be changed with `black  --safe -S -l 100` to

```
('test' 'line')
```

expected

```
('testline')
```

<!--
To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.
--!>

**Comment by ambv** [comment] 2019-03-14 16:47
Thanks! This is a duplicate of #26.

**Closed by ambv** 2019-03-14 16:47 UTC
